config/routes.rb
Mczach::Application.routes.draw do
  root :to => 'applications#index'

  namespace :api do
    namespace :logs do
      post 'log'
    end
  end

  resources :applications, only: %w[index] do
    resource :report, only: %w[show]
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true

  has_many :request_logs

end

app/models/handler.rb
class Handler

  attr_accessor :request_data, :application_name, :time_in_ruby, :time_in_db, :time_rendering, :request_time, :errors
  
  def initialize(request_data)
    self.request_data     = request_data
    self.application_name = request_data.fetch(:application_name, nil).to_s
    self.time_in_ruby     = request_data.fetch(:time_in_ruby, nil)
    self.time_in_db       = request_data.fetch(:time_in_db, nil)
    self.time_rendering   = request_data.fetch(:time_rendering, nil)
    self.request_time     = request_time
    self.errors           = []
  end

  def log
    return false unless check_for_errors
    RequestLog.new.tap do |log|
      log.application      = find_or_create_application
      log.time_in_ruby     = time_in_ruby
      log.time_in_db       = time_in_db
      log.time_rendering   = time_rendering
      log.request_time     = request_time
      log.save!
    end
  end

  def results
    { results: "logged request successfully."}
  end

  def check_for_errors
    instance_values.each do |k, v|
      next if k == 'errors'
      v.blank? ? errors << "#{k} cannot be nil." : next
    end

    errors.empty?
  end

  private

  def find_or_create_application
    @application ||= (Application.find_by_name(application_name) || Application.create!(name: application_name))
  end

  def request_time
    time_rendering.to_f + time_in_db.to_f + time_in_ruby.to_f
  end
end

app/models/request_log.rb
class RequestLog < ActiveRecord::Base

  validates  :time_in_ruby, :time_in_db, :time_rendering, :request_time, presence: true

  belongs_to :application

end

app/controllers/api/logs_controller.rb
class Api::LogsController < ApiController

  def log
    if handler.check_for_errors && handler.log
      render json: handler.results
    else
      render json: {errors: handler.errors}, status: 400
    end
  end

  private

  def handler
    @handler ||= Handler.new(params[:request_data])
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  before_filter :verify_api_key

  private

  def verify_api_key
    return unless Rails.env.production?
    return if params[:api_key] == api_key
    render json: {error: 'Invalid API Key'}, status: 403
  end

  def api_key
    "644721eedb95f223d45b4461a03ea1995e1ffe159d1a1dd3bcfbc89ed0222926"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/applications_controller.rb
# Probably should have picked a different name!
class ApplicationsController < ApplicationController
  
  def index
    @applications = Application.all
  end

  def show
    
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def show
    @application    = Application.find(params[:application_id])
    @report_data    = @application.request_logs.map { |log| [log.time_in_ruby, log.time_in_db, log.time_rendering]}
    @time_in_ruby   = time_in_ruby
    @time_in_db     = time_in_db
    @time_rendering = time_rendering
  end

  private

  def time_in_ruby
    @application.request_logs.pluck(:time_in_ruby)
  end

  def time_in_db
    @application.request_logs.pluck(:time_in_db)
  end

  def time_rendering
    @application.request_logs.pluck(:time_rendering)
  end

  MathError = Class.new(StandardError)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/report_helper.rb
module ReportHelper
  
  def average_time(array)
    sum = array.sum
    length = array.length
    sum / length
  rescue
    MathError 
  end

  MathError = Class.new(StandardError)
end

app/views/applications/index.html.haml
.span3
  .box
    .box-title
      About The Author
    .box-content
      .row-fluid
        .span6
          .img
            = link_to image_tag('zach.jpg', width: "190"), 'http://github.com/wzcolon'
        .span6
          .contact-info
            %h4 Contact Info
            %ul.no-bullets.no-indent
              %li
                %i.icon-briefcase
                704.916.9224
              %li 
                %i.icon-envelope
                = mail_to 'zcolon80@gmail.com', 'Email'
              %li
                %i.icon-share
                = link_to "Github Profile", 'http://github.com/wzcolon'
              %li
                %i.icon-share
                = link_to "LinkedIn Profile", 'http://linkedin.com/pub/zach-colon/40/33/240'
.span9
  .box
    .box-title
      Applications
    .box-content
      %table.table.table-bordered
        %thead
          %tr
            %th Application Name
            %th Number of Requests
        %tbody
          - if !@applications.empty?
            - @applications.each do |app|
              %tr
                %td
                  = link_to app.name, application_report_path(app)
                %td
                  = app.request_logs.count

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>McZach</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <div class="logo">
        <%= link_to "McZach App", root_path %>
      </div>
      <div style="float:right">
        <nav>
        <ul class="nav pull-right">
        </nav>
      </div>
    </div>
  </div>
  </header>
    <body class ="body" id="<%=(params[:controller]).gsub('/', '-')%>-style">
      <div class="container-fluid">
        <div class="row-fluid">
          <% if notice %>
            <div class="alert alert-success"> <%= notice %></div> 
          <% end %>
          <% if alert %>
            <div class="alert alert-error"> <%= alert %></div> 
          <% end %>
          <%= yield %>
        </div>
      </div>
    </body>
  </html>

app/views/reports/_bar_chart.html.haml
:javascript
  $(document).ready(function(){
    var s1 = [#{average_time(@time_in_ruby)}, 0];
    var s2 = [#{average_time(@time_in_db)}, 0];
    var s3 = [#{average_time(@time_rendering)}, 0];
    var ticks = ["#{@application.name} average request breakdown (ms)"];
    plot2 = jQuery.jqplot ('chart2', [s1, s2, s3], 
      {
        stackSeries: true,
        seriesDefaults: {
          renderer: jQuery.jqplot.BarRenderer,
          rendererOptions: {
            barMargin: 60
          },
          pointLabels: {show: true}
        },
        series: [
         {label:'Time in Ruby'},
         {label:'Time in Database'},
         {label:'Time Rendering'}
        ],
        axes: {
          xaxis: {
            renderer: $.jqplot.CategoryAxisRenderer,
            ticks: ticks
          },
          yaxis: {
            padMin: 0
          }
        },
        legend: { 
          show:true, 
          location: 'e',
          placement: 'outside'
        }
    });
  });

app/views/reports/_pie_chart.html.haml
:javascript
  $(document).ready(function(){
    var data = [
      ['Time in Ruby', #{average_time(@time_in_ruby)}], ['Time in Database', #{average_time(@time_in_db)}], ['Time Rendering', #{average_time(@time_rendering)}]
    ];
    var plot1 = jQuery.jqplot ('chart1', [data],
      {
        seriesDefaults: {
          renderer: jQuery.jqplot.PieRenderer,
          rendererOptions: {
            showDataLabels: true
          }
        },
        legend: { show:true, location: 'e' }
      }
    );
  });

app/views/reports/show.html.haml
.span3
  .box
    .box-title
      = "#{@application.name} Menu"
    .box-content
      = link_to "Home", root_path
.span9
  .box
    .box-title
      = @application.name
    .box-content
      #limit
        %h4 Charts show averages of submitted requests.
        #chart1.chart
          = render 'pie_chart'
        #chart2.chart
          = render 'bar_chart'